/**$(function(){
	var footer = '<div class="footer">';
	footer += '<div class="friendLink"><ul>';
	footer += '<li><a href="javascript:;">投资者关系 </a></li>';
	footer += '<li><a href="javascript:;">关于同花顺 </a></li>';
	footer += '<li><a href="javascript:;">软件下载 </a></li>';
	footer += '<li><a href="javascript:;">法律声明 </a></li>';
	footer += '<li><a href="javascript:;">运营许可 </a></li>';
	footer += '<li><a href="javascript:;">内容合作 </a></li>';
	footer += '</ul></div>';
	footer += '<div class="friendLink">CopyrightHithink RoyalFlush Information Network Co.,Ltd. All rights reserved.</div>';
	footer += '<div class="friendLink"> 浙江核新同花顺网络信息股份有限公司版权所有</div>';
	footer += '</div>';
	$("body").append(footer);
});**/
$(function(){
var footer = '<div class="footer">';
        footer += '<div class="footer_up">';
        footer += '<div class="foot_wrap">';
        footer += '<div class="ft_left">';
        footer += '<img alt="" src="images/SK_by_03.png">';
        footer += '<p>医疗投资权威品牌</p>';
        footer += '</div>';
        footer += '<div class="cter">';
        footer += ' <img alt="" src="images/SK_ewm_53.jpg">';
        footer += '</div>';
        footer += ' <div class="ft_right">';
        footer += '<img alt="" src="images/foter2_56.jpg">';
        footer += ' <p><span>联系电话：</span><br>010-54602313</p>';
        footer += '</div>';
        footer += '</div>';
        footer += ' </div>';
        footer += ' <div class="footer_down">';
        footer += ' <ul>';
        footer += '   <li><a href="">关于我们</a></li>';
        footer += '    <li><a href="">加入我们</a></li>';
        footer += '    <li><a href="">联系我们</a></li>';
        footer += '   <li><a href="">帮助支持</a></li>';
        footer += '  <div style="clear: both"></div>';
        footer += ' </ul>';
        footer += ' <p>京ICP备14054333号</p>';
        footer += ' </div>';
        footer += ' </div>';
        $("body").append(footer);
    });